### ISSUE TITLE
Capture points in Mercenary Domination mode will use inconsistent team colors on their cap point model.

### ISSUE THREAD

**Issue by AgitationSkeleton** [openfortress/public-issue-tracker#12]
For example, if a BLU player caps a control point, while the hologram and HUD will always accurately reflect the point's owner, the model of the capture zone is not guaranteed to turn blue, and will randomly turn either neutral or red with no consistency. 
(My best guess is this could have something to do with the addition of Merc team and an oversight with how cap points work?)
![unknown](https://user-images.githubusercontent.com/21989910/188380781-53c3ca6d-fd68-4406-8cbf-2755f82432af.png)

**Comment by RubyTheQuester** [comment]
map issue, not a code issue

**Comment by AgitationSkeleton** [comment]
> map issue, not a code issue

No, these are copied directly from cp_granary, and should work the same way. If a Valve map's own control points don't behave properly when taken wholesale, there is definitely something wrong in the code.

**Comment by RubyTheQuester** [comment]
![image](https://user-images.githubusercontent.com/46036824/189546005-2d6fcfa4-5ef5-43ae-baea-552622a7b364.png)
![image](https://user-images.githubusercontent.com/46036824/189546020-dd8b56cd-4b04-4bd1-8846-7e814106be2e.png)
mdom_noonflow_dev

![image](https://user-images.githubusercontent.com/46036824/189546080-55975c17-6c85-4f9a-bc55-e5c02708cb31.png)
![image](https://user-images.githubusercontent.com/46036824/189546061-d6a0fb92-fdfc-42d7-a9ee-b0bfa912a017.png)
cp_granny

map issue, not code issue
