### ISSUE TITLE
Levelling up in Gun Game crashes game / server

### ISSUE THREAD

**Issue by Bluey0607** [openfortress/public-issue-tracker#17]

**Comment by sapphonie** [comment]
Hello @Bluey0607 , could you please provide a crash dump of some sort, e.g. for the server, thru SourceMod's Accelerator extension, or for the client, in `C:\Program Files (x86)\Steam\dumps` ?

**Comment by Bluey0607** [comment]
Here you go https://www.mediafire.com/file/n28ez9zwcnxaehs/crash_hl2.exe_20220907100911_1.dmp/file

**Comment by Bluey0607** [comment]
Fixed as of revision 11, cheers dev team!
