### ISSUE TITLE
In DM Escort, the former civilian player is given a random class on team change.

### ISSUE THREAD

**Issue by AgitationSkeleton** [openfortress/public-issue-tracker#2]
When attempting to make a "Mercenary VIP" map (VIP Escort where Mercs guard [and attack] the Civilian), the player assigned to Civilian will become a random, possibly non-Merc class on teamchange. This can be caused by scramble, or by map logic declaring teams switch after a victory. In addition, this player can often be misattributed as still being the VIP despite the team and class change, allowing for the attackers to win by their own player being killed as a non-Civ.

Entity affected: of_logic_esc

Images: Non-Civilian "VIP" moved to RED after a round completes, who has been given a new class.
![image](https://user-images.githubusercontent.com/21989910/188260359-ab471952-f53f-4ab1-86d0-70ee95a735ba.png)
![image](https://user-images.githubusercontent.com/21989910/188260362-3ca5107d-0f05-4334-89d6-68f0441a2829.png)
Suiciding as the fake VIP allows RED to win because the game thinks I'm still a Civ on BLU.
![image](https://user-images.githubusercontent.com/21989910/188260363-5903a3da-5ff7-4fbf-a8e7-4c7e1a42d83b.png)
Killing the new real Civilian will not work.
![image](https://user-images.githubusercontent.com/21989910/188260368-4e87d64a-ea7f-4591-b005-a43f19e82339.png)

**Comment by KaydemonLP** [comment]
Internally Fixed, class change and force class gamemodes have been cleaned up.
