### ISSUE TITLE
The Duel "Player VS Player" and "Player wins!" hud elements will frequently get stuck

### ISSUE THREAD

**Issue by Applecakey** [openfortress/public-issue-tracker#24]
This happens frequently when a new round starts. The same happens with the similar looking win screen, which can get stuck on the screen with the result of the previous match when the server changes maps.

![image](https://user-images.githubusercontent.com/113013822/188825729-15a1a4f6-dd3c-4990-aaf4-1957104108fd.png)

**Comment by KaydemonLP** [comment]
This issue has been fixed in an internal testing branch for a while, the branch will eventually be pushed, though it might take a bit before it's stable enough.
