### ISSUE TITLE
sv_lan should be on by default

### ISSUE THREAD

**Issue by w3bb** [openfortress/public-issue-tracker#25]
<del>When I use the ``map`` command, I expect it to create a singleplayer game like other Source engine games.</del> **(They don't.)** Instead it creates a public game anybody can join. Often I'm testing something, and I decide to go AFK, just to find that some guy has joined my game when I get back. I'm not sure if this is intentional or not but it's really annoying. It also exposes the IP address of players, which some might find unacceptable (I don't, IP addresses aren't private information.)

**Comment by Deathreus** [comment]
This is how it operates in all Source Multiplayer games, I do agree to an extent that it should be changed, but there are legitimate cases for starting a local server that's open (You shouldn't have your ports open anyway, you are kneecapping yourself)

**Comment by w3bb** [comment]
Yeah, I misremembered the part about other games having it on. Having to constantly reopen and close ports is pretty annoying, I do host servers on this machine.
