### ISSUE TITLE
Attempting to type in chat the moment you causes loss of control

### ISSUE THREAD

**Issue by bcbwatt** [openfortress/public-issue-tracker#28]
This has happened to me several times over the last few days. 
The moment I die, I press enter to type something. Then I'm unable to type anything or even close the chatbox until the map changes.

**Comment by brysondev** [comment]
If this still happens please provide a video or screenshots as evidence.

**Comment by sapphonie** [comment]
@bcbwatt Reopen this if you can reproduce it on latest version. Thanks!
