### ISSUE TITLE
Camera position bug with realistic hands mode

### ISSUE THREAD

**Issue by RashenKun** [openfortress/public-issue-tracker#29]
Sometimes the camera goes behind the head if the realistic hand view setting is enabled (cl_first_person_uses_world_model 1)
Sorry for the quality of the video, it was originally intended for the bug tracker channel in discord

https://user-images.githubusercontent.com/113209128/189428506-a2d124ec-6022-4c72-9578-f6dda53d45c4.mp4

**Comment by RashenKun** [comment]
I found the setting. This is not a setup, but a command. Called "cl_first_person_uses_world_model 1

**Comment by RubyTheQuester** [comment]
not gonna be fixed
