### ISSUE TITLE
Taunting breaks thirdperson

### ISSUE THREAD

**Issue by tcharchar** [openfortress/public-issue-tracker#33]
For some reason, taunting will place the camera in a random fixed location, unable to move it until taunt again to set it in another random fixed location or if you rejoin the server.
![image](https://user-images.githubusercontent.com/110164189/189515290-0b3d3e45-e2cb-4220-a3fa-a645377236f6.png)

**Comment by KaydemonLP** [comment]
Third person handling has been revamped internally, fixing this issue
