### ISSUE TITLE
Profile pictures display in low quality

### ISSUE THREAD

**Issue by Sloofy** [openfortress/public-issue-tracker#34]
In killcams and while displaying MVPs at the end of games, the game will display a lower quality version of the person's profile picture.

Last I've seen this sort of behaviour, TF2 used to render the class loading icons with their mipmaps which shouldn't be happening.

![Screenshot_20220910_233224](https://user-images.githubusercontent.com/18003771/189515406-13d0b096-5886-482a-92cf-4db5e9f3791e.png)

**Comment by brysondev** [comment]
This is not something we can fix as we don't have access to the SDK 2013 codebase. This is an issue with any sourcemod using it. Closing.
