### ISSUE TITLE
Game fails to mount Team Fortress 2 through an external drive as of Revisions 8-9

### ISSUE THREAD

**Issue by AgitationSkeleton** [openfortress/public-issue-tracker#4]
The paths to TF2 have to be manually declared through gameinfo.txt in order to boot the game, otherwise "Your server is not mounting Team Fortress 2 correctly" will appear as an error message preventing the game from launching as normal.

**Comment by int-72h** [comment]
A workaround is by modifying the gameinfo.txt to have the exact paths.
