### ISSUE TITLE
[Infected] "All-Class" Mode Red players gets forced to zombie merc on death & are not able to change zombie classes (of_forcezombieclass not changing?)

### ISSUE THREAD

**Issue by mixerrules** [openfortress/public-issue-tracker#41]
[I understandable that "All-Class" is not supported mode but there is a small following for it in my community so i will still report and document any issue I run into for brevities sake and just so for other server OPs.]

**Relevant ConVars:**
- of_infection 1
- of_allow_special_classes 1
- of_forceclass 0
- **of_forcezombieclass 0**

**Issue Information:** While in "All-Class" Infected, Red players as other classes then merc die they get switch to zombie merc on blue team, I really don't know what would be causing this but it seems to be related to "of_forcezombieclass" resetting its value to 1 even tho its set to 0 before map change and on server startup via server.cfg. Also if a user is on an "Off-Class" in preround when they get switched to zombie they will keep their class and will be unable to switch out of it, which leads me to think the ConVar is broken.

ConVar of_forcezombieclass showing it's set to 1 after map change even tho it was set to 0 before map change: 
![image](https://user-images.githubusercontent.com/9809371/190534651-8589da75-6ac9-48fc-a9b5-3982209240a0.png)

Example: https://www.youtube.com/watch?v=_8nQEsnAUmA

**Comment by RubyTheQuester** [comment]
check your mutator cfg

**Comment by mixerrules** [comment]
For other server owners: This can be fixed by overwriting it in **config_inf** which is executed by **config_default_inf.cfg** when the infected gamemode is detected by the server.
