### ISSUE TITLE
Normal TF2 maps when jumping whill proppel you in a random direction

### ISSUE THREAD

**Issue by littlefirez** [openfortress/public-issue-tracker#45]
so I decided to put hightower in OF but when i was B-hopping down one of the ramps I was ejected into the Pit and randomly ejected into walls when on other parts of the map. I hope there is A fix to this cause I wanna do a funny on the goofy

**Comment by littlefirez** [comment]
also I cant generate a nav mesh

**Comment by RubyTheQuester** [comment]
can you get a video of such events?
