### ISSUE TITLE
Downloading from a fastdl server fails for players frequently

### ISSUE THREAD

**Issue by LillyWho** [openfortress/public-issue-tracker#48]
I've got a fastdl server running along my OF server, and apparently the client often fails to retrieve the map. It fails with "map is missing". If a player is persistent, eventually they may succeed, or they might not even run into the problem in the first place, only to run into it on the next level change.

The fastdl server is configured correctly and always works for me, so I don't know what could be causing it. Since the server is on my home network, my low ping might have something to do with it. I'm pretty sure that it's not my connection as it's been very consistent on other Source games so far.

http://thenest.dynv6.net:8085/fastdl/of/

**Comment by brysondev** [comment]
Not a bug. 

Fastdl servers require you to use the correct game name for the fastdl folder. (open_fortress)

Ref: https://docs.linuxgsm.com/commands/fastdl
