### ISSUE TITLE
Centered Quad Launcher viewmodel rotated at a -45 degree angle.

### ISSUE THREAD

**Issue by PumpKindOf** [openfortress/public-issue-tracker#49]
![Goofy Ah Quad](https://user-images.githubusercontent.com/87558078/200205633-f769d9a3-c531-44de-9070-6bcca050253f.png)
This causes the arms to be rotated at a -45 degree angle as well.

**Comment by RubyTheQuester** [comment]
it's meant to be like that

**Comment by PumpKindOf** [comment]
Even so it makes any changes to the viewmodel offset commands look strange
