### ISSUE TITLE
Desync between client and server items

### ISSUE THREAD

**Issue by Lucifixion** [openfortress/public-issue-tracker#51]
Holding map specific custom items will cause them to flicker and sometimes do random reload animations

https://user-images.githubusercontent.com/83467229/203416064-16247251-0882-4087-b2f9-ac6530bbf132.mp4

**Comment by brysondev** [comment]
If they don't exist / have invalid data inside the game_items.txt then this tends to happen. 

I'll keep this open for now if anything from our side needs fixing.
