### ISSUE TITLE
Server crashes when you commit suicide

### ISSUE THREAD

**Issue by dhalucario** [openfortress/public-issue-tracker#52]
When playing gungame on dm_boxy, dm_offblast or dm_warhead and you jump into the pit the server just shuts down.
This happens wether sourcemod is installed or not.

The server is running in a pterodactyl docker vm.

**Comment by brysondev** [comment]
If you have yourself god mode and did that then this will happen. Please provide some form of evidence when opening the bug so we can reproduce the issue and try to fix it going forward. 

Closing this for now as I'm 99% sure you had some form of god mode enabled as we're aware of that issue.
