### ISSUE TITLE
CUBEMAPS ISSUE !!

### ISSUE THREAD

**Issue by janblol** [openfortress/public-issue-tracker#56]
yeah one day out of nowhere cubemaps on some maps just broke completely unprompted, just reinstalled and it's still fucked, no idea what causes it.
![image](https://user-images.githubusercontent.com/74105501/216837104-6843ff53-9e5f-4143-b540-78ce8c9343ce.png)

**Comment by brysondev** [comment]
Verify cache for SDK 2013. If its still happening, try playing tf2 and see if the issue occurs there.
