### ISSUE TITLE
Legacy menu and bot behavior broken as of Revamp 13

### ISSUE THREAD

**Issue by Malfaltto** [openfortress/public-issue-tracker#61]
Seems once the update rolled out, the legacy server menu broke, and the bots are acting strangely (running into walls, not firing/swapping weapons, constantly yelling for help even when able to move)

**Comment by brysondev** [comment]
Legacy server creation menu issue is going to be remedied for revision 15. 

As for the bots, they haven't really changed not sure what you're talking about. They're also lower priority at the moment but they will be improved eventually.
