### ISSUE TITLE
[Bug]: Game crashes when loading map

### ISSUE THREAD

**Issue by TheDoomMaster** [openfortress/public-issue-tracker#65]
### Describe the bug.

The game crashes to desktop upon loading a new map, it also happens when starting a server from the main menu.

The loading bar fills up really quickly and then the game crashes as soon as it reaches full.

### Version

rev13

### What server did this occur on?

Deathmatch - Official Openfortress.fun Dedicated Server

### Reproduction steps

```bash
I doubt it can be reproduced, or maybe it can. I don't know much about the Source engine, I wish I could provide more information...
```

### Which operating systems have you used?

Windows

### Expected behavior

Expected behavior is simply the map loading without issue.

**Comment by brysondev** [comment]
If you don't provide reproduction steps, we can't solve the issue.

Please validate your installation with the install batch script or download the zip and merge the files from the zip with your existing install.

Closing this.
