### ISSUE TITLE
Advanced video settings point to non-existent convars

### ISSUE THREAD

**Issue by PumpKindOf** [openfortress/public-issue-tracker#69]
### Describe the bug.

When altering texture quality, enabling HDR tonemapping, or changing DX level the game spits these errors in console:
![image](https://user-images.githubusercontent.com/87558078/230697609-7ad91e3f-3e6f-4b2d-a959-42c168e09365.png)

### Version

rev15

### What server did this occur on?

Map loaded from console

### Reproduction steps

```bash
1. Open settings and click the video tab
2. Press the advanced button
3. Change any of the settings listed above
```

### Which operating systems have you used?

Windows

### Expected behavior

They'll dump errors in the console and not update

### Relevant log output

```shell
ConVarRef mat_dxlevel doesn't point to an existing ConVar
ConVarRef mat_dxlevel doesn't point to an existing ConVar
ConVarRef mat_picmip doesn't point to an existing ConVar
ConVarRef mat_hdr_level doesn't point to an existing ConVar
ConVarRef mat_dxlevel doesn't point to an existing ConVar
ConVarRef mat_dxlevel doesn't point to an existing ConVar
ConVarRef mat_dxlevel doesn't point to an existing ConVar
ConVarRef mat_dxlevel doesn't point to an existing ConVar
ConVarRef mat_picmip doesn't point to an existing ConVar
ConVarRef mat_hdr_level doesn't point to an existing ConVar
ConVarRef mat_dxlevel doesn't point to an existing ConVar
ConVarRef mat_dxlevel doesn't point to an existing ConVar
ConVarRef mat_dxlevel doesn't point to an existing ConVar
```

### Additional context

None

**Comment by RubyTheQuester** [comment]
We were already on the case of this as we saw you talking about these problems within our discord. Thank you for your bug reports!

**Comment by KaydemonLP** [comment]
mat_dxlevel and mat_hdr_level have been discontinued as both are forced to their highest value.
mat_picmip has been superceeded by of_picmip which has extended range (-10 to 10)

The picmip value not changing via the settings is a legitimate bug, so will look into that.

**Comment by KaydemonLP** [comment]
Fixed internally
