### ISSUE TITLE
[Bug]: Games crashes upon joining a server

### ISSUE THREAD

**Issue by Maboi000** [openfortress/public-issue-tracker#71]
### Describe the bug.

I've joined 1 server and after it changed maps the game just crashed, and it keeps crashing whenever I try and join a new server, it usually also is downloading a file each time I go to a server so this might be a custom server bug but i can't really play any of the active games

### Version

rev13

### What server did this occur on?

Deathmatch - Rosemary and Mixermanor.net

### Reproduction steps

```bash
1. Try to join a game
2. Let it download
3. Crash
```

### Which operating systems have you used?

Windows

### Expected behavior

Crashing

### Relevant log output

```shell
Can't post crash dump so uhhhhhh
```

**Comment by KaydemonLP** [comment]
Unable to pinpoint the issue with the given description
