### ISSUE TITLE
[Bug]: Resupply lockers break the loadout in Arsenal (of_mutator 7)

### ISSUE THREAD

**Issue by ToxxyTheTrash** [openfortress/public-issue-tracker#73]
### Describe the bug.

When interacting with a resupply locker with Arsenal enabled, it bugs out your currently holding weapon to a blank one + it breaks viewmodel settings (example from minmode). In this state you cannot use your weapon until you switch to a different weapon. This happens only on Arsenal and not on any different mutator.  
![image](https://github.com/openfortress/public-issue-tracker/assets/28952722/c40e45e8-7ef6-49c0-b50b-30a60527a607)
![image](https://github.com/openfortress/public-issue-tracker/assets/28952722/8cfdede4-7f7d-4613-99fa-635b5d4d9099)

### Version

rev20

### What server did this occur on?

locally hosted server (Raincoat Land Reborn) and recreated in an offline match - used a TF2 map to replicate.

### Reproduction steps

```bash
1. Load map pl_snowycoast for example
2. Change mutator to of_mutator 7
3. Reload the map with map pl_snowycoast
4. Touch resupply locker
```

### Which operating systems have you used?

Windows

### Expected behavior

It's expected for the resupply locker to fully heal you and give you ammo/switch to a different weapon if you've changed loadouts.

**Comment by KaydemonLP** [comment]
Fixed internally
