### ISSUE TITLE
[Bug]: Teleporters do not preserve velocity on linux servers

### ISSUE THREAD

**Issue by Fraeven** [openfortress/public-issue-tracker#74]
### Describe the bug.

When exiting a teleporter on a linux server, the player does not retain their velocity from when they entered. On a comparable windows server, the velocity is maintained.

Note that a linux-specific crash related to teleporters and velocity was reported by us back in 2020. That crash has definitely been fixed, but I'm curious if something related to that fix causes this velocity discrepancy.

Video with description for the original crash bug here:  https://www.youtube.com/watch?v=DD-cUaDTBFA
### Version

rev15

### What server did this occur on?

Locally hosted servers, SCG

### Reproduction steps

```bash
1. Run a Windows server
2. Enter a teleporter (ie. on dm_darkzone)
3. Notice that your velocity is maintained when exiting.

4. Run a Linux server
5. Enter a teleporter  (ie. on dm_darkzone)
6. Notice that your velocity is not maintained when exiting.
```

### Which operating systems have you used?

Linux

### Expected behavior

Teleporter exit velocity is maintained the same on both operating systems.

**Comment by Fraeven** [comment]
We have created a plugin that works around this issue here: https://github.com/SouthernCrossGaming/of-teleporter-velocity-fix

**Comment by sapphonie** [comment]
What the hell

**Comment by KaydemonLP** [comment]
Fixed by sappho
