### ISSUE TITLE
[Bug]: Loading screen tip text is shifted by one character

### ISSUE THREAD

**Issue by worMatty** [openfortress/public-issue-tracker#76]
### Describe the bug.

Tip text on the map load screen is shifted by one character.
![image](https://github.com/openfortress/public-issue-tracker/assets/6231210/86655304-99e0-47ab-a8a4-51ff99441b80)

### Version

rev16

### What server did this occur on?

Death Ventures - 176.57.188.166:27025

### Reproduction steps

```bash
1. Connect to a server
```

### Which operating systems have you used?

Windows

### Expected behavior

The tip text should not be shifted by one character.

**Comment by KaydemonLP** [comment]
Fixed internally
