### ISSUE TITLE
[Bug]: Duel match restarts when spectating player leaves

### ISSUE THREAD

**Issue by MariaR0** [openfortress/public-issue-tracker#81]
### Describe the bug.

A duel match will restart if a player from spectator leaves the server, it will reset the score to zero.

### Version

rev17

### What server did this occur on?

Greenie's Grove | Duel

### Reproduction steps

```bash
1. Have a playable Duel session going (the hardest part).
2. Have a player join spectator.
3. The player in spectator leaves.
4. Congrats you have now reset the round.
```

### Which operating systems have you used?

Windows

### Expected behavior

If the player leaves the match while in spectator during a duel match, the match will reset.

### Additional context

The server this was tested on is running Linux.

**Comment by KaydemonLP** [comment]
Fixed internally
