### ISSUE TITLE
[Bug]: Game crashes if you try and open it while Medal is running

### ISSUE THREAD

**Issue by lavenderfoxx** [openfortress/public-issue-tracker#84]
### Describe the bug.

If you try to open the game while Medal is running, it crashes on startup. The game loads, but a crash error pops up as soon as it's done loading, and your only option is to close the game

### Version

rev13

### What server did this occur on?

None, couldn't get in game

### Reproduction steps

```bash
1. Open OF while Medal is running
2. Crash
3. Profit
```

### Which operating systems have you used?

Windows

### Expected behavior

I was expecting to be able to clip my OF gameplay with Medal, but I cannot do that.

**Comment by KirbNinjaBoy** [comment]
Is that why my game kept fucking crashing?

**Comment by sapphonie** [comment]
This should be fixed as of R19. Please open if not.

Thanks
