### ISSUE TITLE
[Bug]:  The world model for the minigun pickup is textured wrong

### ISSUE THREAD

**Issue by Ratanak45** [openfortress/public-issue-tracker#85]
### Describe the bug.

![20230825082242_1](https://github.com/openfortress/public-issue-tracker/assets/136670046/1bdb2cc1-a81f-461e-9911-f01663c032eb)

### Version

rev13

### What server did this occur on?

Deathmatch - Official Openfortress.fun Dedicated Server

### Reproduction steps

```bash
It's just on the pick up model
```

### Which operating systems have you used?

Windows

### Expected behavior

The texture is incorrectly place on

**Comment by KaydemonLP** [comment]
Known, the model is still WIP
