### ISSUE TITLE
Serverside plugins that execute a sourcemod command can kick the user for netstring spam if they use said command even once.

### ISSUE THREAD

**Issue by AgitationSkeleton** [openfortress/public-issue-tracker#9]
My server runs modified versions of BeTheRobot (The TF2 plugin that lets you do !robot to become an MvM bot) to access various player models, using them can make the server kick you for what it assumes is string spam for some reason.

**Comment by sapphonie** [comment]
@AgitationSkeleton can you purposely get kicked with `sv_spew_stringcmds` on 1 on the server and give me some of the console output? Thanks

**Comment by AgitationSkeleton** [comment]
> @AgitationSkeleton can you purposely get kicked with `sv_spew_stringcmds` on 1 on the server and give me some of the console output? Thanks

![image](https://user-images.githubusercontent.com/21989910/188534704-71c62ef2-c913-4bcd-86db-027c6e67017a.png)

**Comment by sapphonie** [comment]
"issue" with `net_chan_proctime_limit_ms`, set it higher and higher until players don't get kicked.
